In [27]:
import torch

x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(x)


x= torch.unsqueeze(x,0)
print(x)
print(x.shape)
print(x.size())
print(x.ndimension())

x = torch.squeeze(x)
print(x)

x = x.view(9)
print(x)


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
torch.Size([1, 3, 3])
torch.Size([1, 3, 3])
3
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [28]:
w = torch.randn(5,3,dtype=torch.float)
x = torch.tensor([[1.0,2.0],[3.0,4.0],[5.0,6.0]])
b = torch.randn(5,2,dtype=torch.float)
print(w.size())
print(x.size())
print(b.size())


torch.Size([5, 3])
torch.Size([3, 2])
torch.Size([5, 2])


In [31]:
wx = torch.mm(w,x)
print(wx.size())
print(wx)

result = wx+b
print(result.size())
print(result)

torch.Size([5, 2])
tensor([[-3.9850, -4.6035],
        [-5.9884, -7.9990],
        [-6.8579, -9.6412],
        [ 1.5369,  1.0795],
        [ 3.4381,  2.8486]])
torch.Size([5, 2])
tensor([[-4.0239, -5.8891],
        [-5.8559, -7.2360],
        [-7.5198, -9.8447],
        [ 0.7812,  2.1389],
        [ 1.0589,  3.2761]])


In [37]:
w = torch.tensor(1.0, requires_grad=True)
a = w*3
l = a**2

l.backward()
print("l을 w미분 = ",w.grad)

l을 w미분 =  tensor(18.)
